name: Verademo Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}

jobs:
  build:
    runs-on: windows-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Create Build Directory
        run: mkdir _build
        
      - name: Restore Packages
        run: nuget restore *.sln
        
      - name: Build Solution
        run: |
          msbuild.exe *.sln  /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: VerademoBundle
          path: "./_build" 
      
