name: Verademo Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
    permissions:
      contents: read
      packages: write
    
    
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build --configuration Debug
      
      - name: dotnet publish
        run: dotnet publish -c Debug -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
